version: '2'

services:
  web:
    image: php:7-apache
    volumes:
      - ..:/data
      - ../web:/var/www/html
      - ../docker/.env:/var/www/html/.env
      - ../vendor:/var/www/html/vendor
    env_file: .env
    ports:
      - 80:80

  chrome:
    image: selenium/standalone-chrome-debug:2.53.0
    depends_on:
      - web
    environment:
      - no_proxy:localhost
    links:
      - web
      - web:behatgoogleplaceautocomplete.local
    volumes:
      - /dev/shm:/dev/shm
      - ..:/data
    env_file: .env
    ports:
      - 5900:5900
