version: '2'

services:
  web:
    image: php:7-apache
    volumes:
      - ..:/data
      - ../web:/var/www/html
    env_file: .env
    ports:
      - 80:80

  chrome:
    image: selenium/standalone-chrome-debug:3.14.0-dubnium
    depends_on:
      - web
    environment:
      - no_proxy:behatgoogleplaceautocomplete.local
    links:
      - web:behatgoogleplaceautocomplete.local
    volumes:
      - /dev/shm:/dev/shm
    env_file: .env
    ports:
      - 5900:5900
