version: '2'

services:
  app:
    image: php:7.0-fpm
    volumes:
      - ..:/data

  web:
    image: php:7-apache
    depends_on:
      - app
    links:
      - app
    volumes:
      - ..:/data
      - ../web:/var/www/html
      - ../vendor:/var/www/html/vendor
    ports:
      - 80:80

  chrome:
    image: selenium/standalone-chrome-debug:2.53.0
    depends_on:
      - web
    environment:
      - no_proxy:localhost
    links:
      - web
      - web:behatgoogleplaceautocomplete.local
    volumes:
      - /dev/shm:/dev/shm
      - ..:/data
    ports:
      - 5900:5900
